"""add_deleted_at_column

Revision ID: 5380bc4afe2e
Revises: d491c7059c4c
Create Date: 2026-02-17 20:20:51.270962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5380bc4afe2e'
down_revision: Union[str, Sequence[str], None] = 'd491c7059c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'deleted_at')
    # ### end Alembic commands ###
